

export const SAMPLE_PRODUCTS = [
  { id: '1', name: 'classicNewYorkCheesecake', description: 'desc.classicNewYorkCheesecake', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/new-york-cheesecake.jpg', category: 'cheese_cakes', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '2', name: 'strawberryCheesecake', description: 'desc.strawberryCheesecake', price: 12.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/strawberry-cheesecake.jpg', category: 'cheese_cakes', inStock: true, rating: 4.9, reviews: 89, tags: ['french', 'butter', 'artisan'] },
  { id: '3', name: 'basqueBurntCheesecake', description: 'desc.basqueBurntCheesecake', price: 10.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/BurntBasque.jpg', category: 'cheese_cakes', inStock: true, rating: 4.7, reviews: 156, tags: ['organic', 'brown', 'pasture-raised'] },
  { id: '4', name: 'blueberryCheesecake', description: 'desc.blueberryCheesecake', price: 15.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/blueberry-cheesecake.avif', category: 'cheese_cakes', inStock: false, rating: 4.6, reviews: 67, tags: ['chocolate', 'danish', 'sweet'] },
  { id: '5', name: 'tokyoFiveCheese', description: 'desc.tokyoFiveCheese', price: 18.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/tokyocheese.jpg', category: 'cheese_cakes', inStock: true, rating: 4.9, reviews: 43, tags: ['duck', 'heritage', 'gourmet'] },
  { id: '6', name: 'tiramisuClassic', description: 'desc.tiramisuClassic', price: 22.99, image: '/tiramisu.jpg', category: 'chiffon_cakes', inStock: true, rating: 4.8, reviews: 92, tags: ['almond', 'cream', 'light'] },
  { id: '7', name: 'bakedHoneyCheesecake', description: 'desc.bakedHoneyCheesecake', price: 24.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/Honey-Baked.jpg', category: 'chiffon_cakes', inStock: true, rating: 4.9, reviews: 28, tags: ['quail', 'gourmet', 'delicate'] },
  { id: '8', name: 'whiteChiffonBase', description: 'desc.whiteChiffonBase', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/white-chiffon.jpeg', category: 'chiffon_cakes', inStock: true, rating: 4.7, reviews: 156, tags: ['sourdough', 'artisan', 'bread'] },
  { id: '9', name: 'chocolateChiffonBase', description: 'desc.chocolateChiffonBase', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/Chocolate-Chiffon-Cake.jpg', category: 'chiffon_cakes', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '10', name: 'yuzuMatchaCheesecake', description: 'desc.yuzuMatchaCheesecake', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/yuzu-matcha.jpg', category: 'chiffon_cakes', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '11', name: 'lemonTart', description: 'desc.lemonTart', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/lemon-tarte.webp', category: 'french_tarts', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '12', name: 'chocolateTart', description: 'desc.chocolateTart', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/chocolate-tart.webp', category: 'french_tarts', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '13', name: 'taroTart', description: 'desc.taroTart', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/taro-tarts.jpg', category: 'french_tarts', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '14', name: 'frenchFlowerTartLemon', description: 'desc.frenchFlowerTartLemon', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/French-Lemon-Tart.jpg', category: 'french_tarts', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '15', name: 'frenchFlowerTartChocolate', description: 'desc.frenchFlowerTartChocolate', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/tarte-au-chocolat.jpg', category: 'french_tarts', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '16', name: 'pineapplePuffVanilla', description: 'desc.pineapplePuffVanilla', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/Pineapple_Puffs.jpeg', category: 'cream_puffs', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '17', name: 'donutStrawberry', description: 'desc.donutStrawberry', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/donuts.webp', category: 'cream_puffs', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '18', name: 'donutChocolate', description: 'desc.donutChocolate', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/donut-choco.jpg', category: 'cream_puffs', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '19', name: 'caneleOriginal', description: 'desc.caneleOriginal', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/Canele.jpg', category: 'cream_puffs', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] },
  { id: '20', name: 'frenchMadeleineOriginal', description: 'desc.frenchMadeleineOriginal', price: 8.99, image: 'https://umanjtaxxtkqywmgliuu.supabase.co/storage/v1/object/public/cakes/French-Madeleines-Cookies.jpg', category: 'cream_puffs', inStock: true, rating: 4.8, reviews: 124, tags: ['organic', 'free-range', 'local'] }
];


